// Generated by `storyspec gen` from spec.md. Do not edit.
export const gen = {
  storyId: 'S-007',
  title: 'Code no story claims is reported',
  scenarios: {
    'S-007.1': 'Code no story reaches is reported',
    'S-007.2': 'Code joined to a story\'s code by imports is claimed',
    'S-007.3': 'Code listed as unspecified isn\'t reported',
    'S-007.4': 'Tests, build output, config and package markers aren\'t code to claim',
    'S-007.5': 'Where imports can\'t be read, a story must name the file',
  },
} as const

export type ScenarioId = keyof typeof gen.scenarios
