// Generated by `storyspec gen` from spec.md. Do not edit.
export const gen = {
  storyId: 'S-002',
  title: 'Member lists their notes',
  scenarios: {
    'S-002.1': 'Only my notes',
    'S-002.2': 'Newest first',
    'S-002.3': { title: 'The list reads well on a phone', proof: ['manual'] },
  },
} as const

export type ScenarioId = keyof typeof gen.scenarios
