// Generated by `storyspec gen` from spec.md. Do not edit.
export const gen = {
  storyId: 'S-001',
  title: 'Do thing',
  scenarios: {
    'S-001.1': 'Does it',
    'S-001.2': 'Does it twice',
  },
} as const

export type ScenarioId = keyof typeof gen.scenarios
