// Generated by `storyspec gen` from spec.md. Do not edit.
export const gen = {
  storyId: 'S-003',
  title: 'A tier reads several reports',
  scenarios: {
    'S-003.1': 'Results from every listed report count',
    'S-003.2': 'A failure in any listed report fails the trace',
    'S-003.3': 'A listed report the run didn\'t write is skipped',
    'S-003.4': 'A run that wrote none of its reports fails',
  },
} as const

export type ScenarioId = keyof typeof gen.scenarios
