// Generated by `storyspec gen` from spec.md. Do not edit.
export const gen = {
  storyId: 'S-005',
  title: 'Layer rules read imports in any language',
  scenarios: {
    'S-005.1': 'Python imports resolve to the repo\'s files',
    'S-005.2': 'A Python layer violation is reported',
    'S-005.3': 'Swift imports resolve to package targets',
    'S-005.4': 'Tests in other languages may name their scenarios',
  },
} as const

export type ScenarioId = keyof typeof gen.scenarios
