// Generated by `storyspec gen` from spec.md. Do not edit.
export const gen = {
  storyId: 'S-009',
  title: 'Generated scenario files are for TypeScript',
  scenarios: {
    'S-009.1': 'A new story in a TypeScript project needs one',
    'S-009.2': 'A story in a project that isn\'t TypeScript doesn\'t',
    'S-009.3': 'A story with TypeScript in its folder always does',
  },
} as const

export type ScenarioId = keyof typeof gen.scenarios
