// Generated by `storyspec gen` from spec.md. Do not edit.
export const gen = {
  storyId: 'S-006',
  title: 'A spec records its decisions',
  scenarios: {
    'S-006.1': 'A decision pinned by a scenario is accepted',
    'S-006.2': 'A decision pinned by a missing scenario is an error',
    'S-006.3': 'A decision marked free is accepted',
    'S-006.4': 'A decision neither pinned nor free is a warning',
    'S-006.5': 'TRACE.md lists the decisions',
  },
} as const

export type ScenarioId = keyof typeof gen.scenarios
