// spec.md → scenarios.gen.ts, so tests written with story() must cover exactly the spec's scenarios.
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { isTypeScript, type Story } from './trace/scan.js'

export const GEN_FILE = 'scenarios.gen.ts'

const quote = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`

export const renderGen = (story: Story) => {
  // A scenario proven only locally stays a plain title, so projects that never declare tiers see no change.
  const lines = story.scenarios.map(s => s.proof.length === 1 && s.proof[0] === 'local'
    ? `    ${quote(s.id)}: ${quote(s.title || s.id)},`
    : `    ${quote(s.id)}: { title: ${quote(s.title || s.id)}, proof: [${s.proof.map(quote).join(', ')}] },`)
  return [
    '// Generated by `storyspec gen` from spec.md. Do not edit.',
    'export const gen = {',
    `  storyId: ${quote(story.id)},`,
    `  title: ${quote(story.front.title ?? '')},`,
    '  scenarios: {',
    ...lines,
    '  },',
    '} as const',
    '',
    'export type ScenarioId = keyof typeof gen.scenarios',
    '',
  ].join('\n')
}

export type GenStatus = { story: string; file: string; state: 'fresh' | 'stale' | 'missing' }

// The generated file types TypeScript tests. A story with TypeScript in its folder gets one; so does one with nothing
// there yet in a TypeScript project (tsconfig.json at the root, or TypeScript in any story's folder), whose use case is
// still to be written. A story implemented elsewhere (implementedBy:), or in a project that isn't TypeScript (Swift,
// Python), has nothing to type.
const typed = (s: Story, tsProject: boolean) =>
  [...s.code, ...s.tests].some(f => isTypeScript(f.path)) || (tsProject && s.implementedBy.length === 0)

export const genStatus = (root: string, stories: Story[]): GenStatus[] =>
  stories.filter(s => s.hasSpecMd && typed(s, existsSync(join(root, 'tsconfig.json'))
    || stories.some(x => [...x.code, ...x.tests].some(f => isTypeScript(f.path))))).map(s => {
    const file = join(s.dir, GEN_FILE)
    const abs = join(root, file)
    const state = !existsSync(abs) ? 'missing' : readFileSync(abs, 'utf8') === renderGen(s) ? 'fresh' : 'stale'
    return { story: s.id, file, state }
  })

export const writeGen = (root: string, stories: Story[]) =>
  genStatus(root, stories).filter(g => g.state !== 'fresh').map(g => {
    const story = stories.find(s => s.id === g.story)!
    writeFileSync(join(root, g.file), renderGen(story))
    return g
  })
