// spec.md → scenarios.gen.ts, so tests written with story() must cover exactly the spec's scenarios.
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { Story } from './trace/scan.js'

export const GEN_FILE = 'scenarios.gen.ts'

const quote = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`

export const renderGen = (story: Story) => {
  const lines = story.scenarios.map(s => `    ${quote(s.id)}: ${quote(s.title || s.id)},`)
  return [
    '// Generated by `storyspec gen` from spec.md. Do not edit.',
    'export const gen = {',
    `  storyId: ${quote(story.id)},`,
    `  title: ${quote(story.front.title ?? '')},`,
    '  scenarios: {',
    ...lines,
    '  },',
    '} as const',
    '',
    'export type ScenarioId = keyof typeof gen.scenarios',
    '',
  ].join('\n')
}

export type GenStatus = { story: string; file: string; state: 'fresh' | 'stale' | 'missing' }

export const genStatus = (root: string, stories: Story[]): GenStatus[] =>
  stories.filter(s => s.hasSpecMd).map(s => {
    const file = join(s.dir, GEN_FILE)
    const abs = join(root, file)
    const state = !existsSync(abs) ? 'missing' : readFileSync(abs, 'utf8') === renderGen(s) ? 'fresh' : 'stale'
    return { story: s.id, file, state }
  })

export const writeGen = (root: string, stories: Story[]) =>
  genStatus(root, stories).filter(g => g.state !== 'fresh').map(g => {
    const story = stories.find(s => s.id === g.story)!
    writeFileSync(join(root, g.file), renderGen(story))
    return g
  })
