"""What the use cases need from the outside world. Each port has a memory adapter and a Postgres adapter, and a
contract suite (tests/contracts) both must pass."""
from __future__ import annotations

from datetime import datetime
from typing import Protocol

from app.domain.model import Article, Comment, Page, User


class UserStore(Protocol):
    def add(self, username: str, email: str, password_hash: str) -> User: ...
    def by_id(self, user_id: int) -> User | None: ...
    def by_username(self, username: str) -> User | None: ...
    def by_email(self, email: str) -> User | None: ...
    def save(self, user: User) -> User: ...


class FollowStore(Protocol):
    def follow(self, follower_id: int, followee_id: int) -> None: ...
    def unfollow(self, follower_id: int, followee_id: int) -> None: ...
    def follows(self, follower_id: int, followee_id: int) -> bool: ...
    def followees(self, follower_id: int) -> list[int]: ...


class ArticleStore(Protocol):
    def add(self, slug: str, title: str, description: str, body: str, author_id: int, tags: tuple[str, ...], at: datetime) -> Article: ...
    def by_slug(self, slug: str) -> Article | None: ...
    def save(self, article: Article) -> Article: ...
    def delete(self, article_id: int) -> None: ...
    def list(self, page: Page, *, tag: str | None = None, author_ids: list[int] | None = None, favorited_by: int | None = None) -> tuple[list[Article], int]:
        """Newest first. `author_ids`: only those authors' articles (an empty list means none). Returns the page and the total."""
        ...
    def tags(self) -> list[str]: ...
    def favorite(self, user_id: int, article_id: int) -> None: ...
    def unfavorite(self, user_id: int, article_id: int) -> None: ...
    def favorited(self, user_id: int, article_id: int) -> bool: ...
    def favorites_count(self, article_id: int) -> int: ...


class CommentStore(Protocol):
    def add(self, article_id: int, author_id: int, body: str, at: datetime) -> Comment: ...
    def for_article(self, article_id: int) -> list[Comment]: ...
    def by_id(self, comment_id: int) -> Comment | None: ...
    def delete(self, comment_id: int) -> None: ...


class Clock(Protocol):
    def now(self) -> datetime: ...


class Passwords(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, hashed: str) -> bool: ...


class Tokens(Protocol):
    def issue(self, user_id: int) -> str: ...
    def read(self, token: str) -> int | None:
        """The user the token was issued to, or None when it's invalid or expired."""
        ...
