// Generated by `storyspec gen` from spec.md. Do not edit.
export const gen = {
  storyId: 'S-004',
  title: 'The config schema describes every setting',
  scenarios: {
    'S-004.1': 'The schema lists exactly the config\'s settings',
    'S-004.2': 'Tier reports may be one path or several',
  },
} as const

export type ScenarioId = keyof typeof gen.scenarios
