// Generated by `storyspec gen` from spec.md. Do not edit.
export const gen = {
  storyId: 'S-001',
  title: 'Trace reads JUnit reports',
  scenarios: {
    'S-001.1': 'Scenario IDs written the way the language allows',
    'S-001.2': 'A test that names no tier ran in the reporting tier',
    'S-001.3': 'A name with no scenario proves nothing',
    'S-001.4': 'A Python project is clean from its JUnit report',
    'S-001.5': 'A failed test fails its scenario',
    'S-001.6': 'A failure message keeps its line breaks',
    'S-001.7': 'A scenario no test ran is untested',
    'S-001.8': 'A test naming a scenario the spec lacks is an orphan',
    'S-001.9': 'A failure outside any scenario fails the trace',
    'S-001.10': 'A skipped test proves nothing',
    'S-001.11': 'Another tier records what its command ran',
  },
} as const

export type ScenarioId = keyof typeof gen.scenarios
