import type { Finding, PortCoverage } from './rules.js'
import type { Repo } from './scan.js'

export type TraceRow = {
  epic: string
  story: string
  title: string
  status: string
  version: string
  implementation: string
  scenarios: { id: string; title: string; tested: boolean; outcome: 'pass' | 'fail' | 'not-run' }[]
}

export const rows = (repo: Repo): TraceRow[] =>
  repo.stories.map(s => {
    const impl = s.code.find(f => f.text.includes(`@implements ${s.id}`))
    return {
      epic: s.front.epic ?? '',
      story: s.id,
      title: s.front.title ?? '',
      status: s.front.status ?? '',
      version: s.front.version ?? '',
      implementation: impl?.path ?? '',
      scenarios: s.scenarios.map(sc => ({
        id: sc.id,
        title: sc.title,
        tested: s.testedIds.includes(sc.id),
        outcome: repo.outcomes.get(sc.id) ?? 'not-run',
      })),
    }
  })

const mark = (s: TraceRow['scenarios'][number]) =>
  !s.tested ? '✗ no test' : s.outcome === 'pass' ? '✓ pass' : s.outcome === 'fail' ? '✗ fail' : '· not run'

export const table = (rs: TraceRow[]) => [
  '| Epic | Story | Status | v | Implementation | Scenario | Test |',
  '|---|---|---|---|---|---|---|',
  ...rs.flatMap(r => {
    const head = `| ${r.epic} | ${r.story} ${r.title} | ${r.status} | ${r.version} | ${r.implementation} |`
    if (r.scenarios.length === 0) return [`${head} — | ✗ no scenarios |`]
    return r.scenarios.map((s, i) => i === 0 ? `${head} ${s.id} | ${mark(s)} |` : `| | | | | | ${s.id} | ${mark(s)} |`)
  }),
].join('\n')

export const portTable = (ports: PortCoverage[]) => [
  '| Port | Defined in | Adapters | Contract tests run |',
  '|---|---|---|---|',
  ...ports.map(p => `| ${p.port} | ${p.file} | ${p.adapters.join('<br>') || '✗ none'} | ${p.contractTests.join('<br>') || '✗ none'} |`),
].join('\n')

export const traceMarkdown = (rs: TraceRow[], ports: PortCoverage[] = []) =>
  ['# Trace', '', 'Generated by `storyspec trace`. Do not edit.', '', '## Stories', '', table(rs), '',
    ...(ports.length ? ['## Ports', '', portTable(ports), ''] : [])].join('\n')

export const findingsText = (findings: Finding[]) => {
  const fmt = (f: Finding) => `  - [${f.rule}] ${f.file ? `${f.file}: ` : ''}${f.message}`
  const warnings = findings.filter(f => f.severity === 'warning')
  const errors = findings.filter(f => f.severity === 'error')
  return [
    warnings.length ? `\n${warnings.length} warning(s):\n${warnings.map(fmt).join('\n')}` : '',
    errors.length ? `\n${errors.length} problem(s):\n${errors.map(fmt).join('\n')}` : '',
  ].filter(Boolean).join('\n')
}
