// Generated by `storyspec gen` from spec.md. Do not edit.
export const gen = {
  storyId: 'S-002',
  title: 'A story names the files that implement it',
  scenarios: {
    'S-002.1': 'Listed files that exist implement the story',
    'S-002.2': 'A listed file that doesn\'t exist is an error',
    'S-002.3': 'Without implementedBy or @implements there is no implementation',
  },
} as const

export type ScenarioId = keyof typeof gen.scenarios
