// Generated by `storyspec gen` from spec.md. Do not edit.
export const gen = {
  storyId: 'S-001',
  title: 'Member saves a note',
  scenarios: {
    'S-001.1': 'Valid note is saved',
    'S-001.2': 'Empty title is rejected',
    'S-001.3': 'Title is trimmed',
  },
} as const

export type ScenarioId = keyof typeof gen.scenarios
