// Generated by `storyspec gen` from spec.md. Do not edit.
export const gen = {
  storyId: 'S-008',
  title: 'A story can be built after others',
  scenarios: {
    'S-008.1': 'after: is shown in TRACE.md',
    'S-008.2': 'after: naming a missing story is an error',
    'S-008.3': 'A story can\'t come after itself',
    'S-008.4': 'A loop is an error',
  },
} as const

export type ScenarioId = keyof typeof gen.scenarios
