#!/usr/bin/env node
// npm create storyspec@latest <dir> [--no-example] [--no-install]
import { spawnSync } from 'node:child_process'
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { basename, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const args = process.argv.slice(2)
const flags = new Set(args.filter(a => a.startsWith('--')))
const dirArg = args.find(a => !a.startsWith('--'))

if (!dirArg || flags.has('--help')) {
  console.log('Usage: npm create storyspec@latest <dir> [-- --no-example] [-- --no-install]')
  process.exit(dirArg ? 0 : 1)
}

const target = resolve(dirArg)
if (existsSync(target) && readdirSync(target).length > 0) {
  console.error(`${target} exists and isn't empty.`)
  process.exit(1)
}

const here = fileURLToPath(new URL('.', import.meta.url))
const own = JSON.parse(readFileSync(join(here, 'package.json'), 'utf8'))
const template = join(here, 'template')
if (!existsSync(template)) {
  console.error('This create-storyspec build has no bundled template. Run `npm run build` in packages/create-storyspec.')
  process.exit(1)
}

cpSync(template, target, { recursive: true })
if (existsSync(join(target, 'gitignore'))) renameSync(join(target, 'gitignore'), join(target, '.gitignore'))

const pkgPath = join(target, 'package.json')
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
pkg.name = basename(target).toLowerCase().replace(/[^a-z0-9-_.]/g, '-')
pkg.devDependencies.storyspec = process.env.STORYSPEC_SPEC ?? `^${own.version}`

if (flags.has('--no-example')) stripExample(target, pkg)
writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n')

if (!flags.has('--no-install')) {
  console.log('Installing dependencies…')
  const r = spawnSync('npm', ['install'], { cwd: target, stdio: 'inherit', shell: process.platform === 'win32' })
  if (r.status !== 0) process.exit(r.status ?? 1)
}

const rel = dirArg
console.log(`
Created ${rel}.

  cd ${rel}${flags.has('--no-install') ? '\n  npm install' : ''}
  npm run check                       # typecheck + tests + trace
  npm run story -- "Your first story"  # or /story "…" in Claude Code
${flags.has('--no-example') ? '' : '  npm run dev                         # example notes API on :3000\n'}
Read AGENTS.md for the rules, and README.md for how it fits together.
`)

// Leaves the structure, tooling and docs, but no example domain: one draft story to start from.
function stripExample(root, pkg) {
  const remove = [
    'stories', 'src/domain/note.ts', 'src/ports', 'src/adapters', 'src/presenters', 'src/entry/http.ts',
    'test/fakes', 'test/contracts',
  ]
  for (const p of remove) rmSync(join(root, p), { recursive: true, force: true })
  for (const d of ['src/ports', 'src/adapters', 'src/presenters', 'test/fakes', 'test/contracts']) {
    mkdirSync(join(root, d), { recursive: true })
    writeFileSync(join(root, d, '.gitkeep'), '')
  }
  writeFileSync(join(root, 'src/entry/composition.ts'), [
    '// The only place that wires adapters into stories.',
    'export const compose = () => ({})',
    '',
    'export type App = ReturnType<typeof compose>',
    '',
  ].join('\n'))
  delete pkg.scripts.dev

  const story = join(root, 'stories/S-001-first-story')
  mkdirSync(story, { recursive: true })
  const today = new Date().toISOString().slice(0, 10)
  writeFileSync(join(story, 'story.md'), `---
id: S-001
title: First story
epic:
status: draft
version: 1
---

As a <role>, I want <capability>,
so that <outcome>.

## Revisions

- v1 (${today}): initial
`)
  writeFileSync(join(story, 'spec.md'), `# S-001 spec

### Requirement: <one behaviour> {#S-001}

WHEN <trigger> THE SYSTEM SHALL <response>.

#### Scenario: <case> {#S-001.1}

- GIVEN <state>
- WHEN <action>
- THEN <observable result>
`)
  writeFileSync(join(story, 'scenarios.gen.ts'), `// Generated by \`storyspec gen\` from spec.md. Do not edit.
export const gen = {
  storyId: 'S-001',
  title: 'First story',
  scenarios: {
    'S-001.1': '<case>',
  },
} as const

export type ScenarioId = keyof typeof gen.scenarios
`)
}
